name: "recommend mobpro"
on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event_name != 'issue_comment' || github.event.issue.pull_request
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - uses: tnyo43/recommend-mobpro-action@v0.0.1
        with:
          threshold: 4
