name: "recommend mobpro"
on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  recommend-mobpro:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: tnyo43/recommend-mobpro-action@v1
        with:
          threshold: 4
